### ISSUE TITLE
Incompatibility with LevelZ

### ISSUE THREAD

**Issue by Onnei** [nicofighter45/FabricVanaMod#5]
when i try to launch the game this error occures the minecarft window opens but crashes after like 5 seconds

i shortend the log because of githubs character limit

Mods:
  [✔] 2032-world-height-1.17+
  [✔] adventureredefined-0.1.0-1.20.1
  [✔] AmbientSounds_FABRIC_v6.0.1_mc1.20.1
  [✔] Amplified_Nether_1.20.4_v1.2.4
  [✔] architectury-9.2.14-fabric
  [✔] auditory-0.0.6-1.20.1
  [✔] autotag-2.0.2+1.20
  [✔] bettercombat-fabric-1.8.5+1.20.1
  [✔] Boids-1.1.1
  [✔] c2me-fabric-mc1.20.1-0.2.0+alpha.11.5
  [✔] carryon-fabric-1.20.1-2.1.2.7
  [✔] Chunky-1.3.146
  [✔] cloth-config-11.1.118-fabric
  [✔] Clumps-fabric-1.20.1-12.0.0.4
  [✔] collective-1.20.1-7.57
  [✔] completeconfig-2.5.0
  [✔] Continents_1.20.4_v1.1.4
  [✔] continuity-3.0.0-beta.5+1.20.1
  [✔] Controlling-fabric-1.20.1-12.0.2
  [✔] CreativeCore_FABRIC_v2.11.28_mc1.20.1
  [✔] cristellib-1.1.5-fabric
  [✔] dangerclose-merged-1.20.1-3.0.2
  [✔] DistantHorizons-fabric-2.0.4-a-dev-1.20.1
  [✔] dungeons-and-taverns-3.0.3.f
  [✔] dungeons-and-taverns-pillager-outpost-rework-1.1
  [✔] dynamiccrosshair-7.4.4+1.20-fabric
  [✔] DynamicSurroundings-Fabric-1.20.1-0.3.3
  [✔] EasyAnvils-v8.0.2-1.20.1-Fabric
  [✔] EasyMagic-v8.0.1-1.20.1-Fabric
  [✔] eating-animation-1.20+1.9.61
  [✔] enhancedblockentities-0.9+1.20
  [✔] EnhancedVisuals_FABRIC_v1.7.2_mc1.20.1
  [✔] entity_model_features_fabric_1.20.1-2.0.2
  [✔] entity_texture_features_fabric_1.20.1-6.0.1
  [✔] entityculling-fabric-1.6.2-mc1.20.1
  [✔] essential_1-3-2-3_fabric_1-20-1
  [✔] fabric-api-0.92.1+1.20.1
  [✔] fabric-language-kotlin-1.10.20+kotlin.1.9.24
  [✔] fallingleaves-1.15.6+1.20.1
  [✔] ferritecore-6.0.1-fabric
  [✔] firstperson-fabric-2.3.4-mc1.20.1
  [✔] ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric
  [✔] herdspanic-1.1.0
  [✔] HopoBetterRuinedPortals-[1.20-1.20.2]-1.3.7
  [✔] HopoBetterUnderwaterRuins-[1.20-1.20.2]-1.1.4b
  [✔] Iceberg-1.20.1-fabric-1.1.18
  [✔] Incendium_1.20.4_v5.3.4
  [✔] indium-1.0.30+mc1.20.4
  [✔] iris-1.7.0+mc1.20.1
  [✔] Kiwi-1.20.1-fabric-11.6.2
  [✔] krypton-0.2.3
  [✔] lazydfu-0.1.3
  [✔] leawind_third_person-v2.0.8-beta.5-mc1.20.1-fabric
  [✔] LegendaryTooltips-1.20.1-fabric-1.4.5
  [✔] LetSleepingDogsLie-1.20.1-Fabric-1.2.0
  [✔] levelz-1.4.13
  [✔] libz-1.0.3
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] mobs-attempt-parkour-0.5.2-1.20
  [✔] modelfix-1.15-fabric
  [✔] modmenu-7.2.2
  [✔] monolib-fabric-1.20.1-1.1.0
  [✔] moreculling-1.20.4-0.24.0
  [✔] MouseTweaks-fabric-mc1.20-2.26
  [✔] mru-0.4.0+1.20
  [✔] notenoughanimations-fabric-1.7.3-mc1.20.1
  [✔] notenoughcrashes-4.4.7+1.20.1-fabric
  [✔] Nullscape_1.20.4_v1.2.4
  [✔] nvidium-0.2.6-beta
  [✔] PassableFoliage-1.20.1-fabric-8.2.1
  [✔] physics-mod-pro-v169-fabric-1.20.1
  [✔] PickUpNotifier-v8.0.0-1.20.1-Fabric
  [✔] player-animation-lib-fabric-1.0.2-rc1+1.20
  [✔] PresenceFootsteps-1.9.3
  [✔] Prism-1.20.1-fabric-1.0.5
  [✔] PuzzlesLib-v8.0.15-1.20.1-Fabric
  [✔] reeses_sodium_options-1.7.2+mc1.20.1-build.101
  [✔] rpgz-0.6.0
  [✔] Searchables-fabric-1.20.1-1.0.3
  [✔] sodium-extra-0.5.4+mc1.20.1-build.115
  [✔] sodium-fabric-0.5.8+mc1.20.1
  [✔] sol_valheim-1.1.1-4
  [✔] solid_mobs_fabric.1.19.4+1.20-1.7.1
  [✔] sound-physics-remastered-fabric-1.20.1-1.3.1
  [✔] Sounds-0.7.0+1.20.1
  [✔] spawnanimations-v1.9.4-mc1.17x-1.20x-mod
  [✔] spell_power-0.10.2+1.20.1
  [✔] starlight-1.1.2+fabric.dbc156f
  [✔] tectonic-fabric-1.20-2.3.4
  [✔] Terralith_1.20_v2.5.0
  [✔] tiered-1.3.3
  [✔] Towns-and-Towers-1.12-Fabric+Forge
  [✔] TravelersTitles-1.20-Fabric-4.0.2
  [✔] vanadium-0.1.675
  [✔] villagernames-1.20.1-7.3
  [✔] VisualWorkbench-v8.0.0-1.20.1-Fabric
  [✔] weaponmaster-client-only-fabric-1.20.1-3.0.5
  [✔] YungsApi-1.20-Fabric-4.0.5
  [✔] YungsBetterDesertTemples-1.20-Fabric-3.0.3
  [✔] YungsBetterDungeons-1.20-Fabric-4.0.4
  [✔] YungsBetterEndIsland-1.20-Fabric-2.0.6
  [✔] YungsBetterJungleTemples-1.20-Fabric-2.0.5
  [✔] YungsBetterMineshafts-1.20-Fabric-4.0.4
  [✔] YungsBetterNetherFortresses-1.20-Fabric-2.0.6
  [✔] YungsBetterOceanMonuments-1.20-Fabric-3.0.4
  [✔] YungsBetterStrongholds-1.20-Fabric-4.0.3
  [✔] YungsBetterWitchHuts-1.20-Fabric-3.0.3
  [✔] YungsBridges-1.20-Fabric-4.0.3
  [✔] YungsExtras-1.20-Fabric-4.0.3

[17:53:51] [Render thread/ERROR]: Couldn't load pack metadata
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Unterminated string at line 6 column 2 path $.pack.description
	at net.minecraft.class_3518.method_47993(class_3518.java:526) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15267(class_3518.java:531) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15274(class_3518.java:593) ~[client-intermediary.jar:?]
	at net.minecraft.class_3518.method_15255(class_3518.java:601) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14392(class_3255.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_3255.method_14407(class_3255.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45274(class_3288.java:71) ~[client-intermediary.jar:?]
	at net.minecraft.class_3288.method_45275(class_3288.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45272(class_3279.java:51) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_45271(class_3279.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_3279.method_14453(class_3279.java:47) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_29212(class_3283.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_3283.method_14445(class_3283.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:513) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 6 column 2 path $.pack.description
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1042) ~[gson-2.10.jar:?]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.readTerminal(TypeAdapters.java:747) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:791) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:725) ~[gson-2.10.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$34$1.read(TypeAdapters.java:1007) ~[gson-2.10.jar:?]
	at net.minecraft.class_3518.method_47993(class_3518.java:524) ~[client-intermediary.jar:?]
	... 20 more
[17:53:51] [Render thread/WARN]: Missing metadata in pack file/Brixel 3.1 64x - unpack me!
[17:53:51] [Render thread/WARN]: Missing metadata in pack file/Brixel 3.1 64x BSL - unpack this in your .minecraft folder.zip.zip
[17:53:51] [Render thread/INFO]: enabled vertex attrib rendering path
[17:53:52] [Render thread/WARN]: Method overwrite conflict for getModel in fabric-model-loading-api-v1.mixins.json:BakedModelManagerMixin from mod fabric-model-loading-api-v1, previously written by foundationgames.enhancedblockentities.mixin.BakedModelManagerMixin. Skipping method.
[17:53:52] [Render thread/INFO]: Hardware information:
[17:53:52] [Render thread/INFO]: CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
[17:53:52] [Render thread/INFO]: GPU: NVIDIA GeForce RTX 4070/PCIe/SSE2 (Supports OpenGL 3.2.0 NVIDIA 552.22)
[17:53:52] [Render thread/INFO]: OS: Windows 11 (10.0)
[17:53:52] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_3295 in sodium.mixins.json:core.render.world.WorldRendererMixin from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.
[17:53:53] [Render thread/WARN]: @ModifyConstant conflict. Skipping vanadium.mixins.json:client.InGameHudMixin from mod vanadium->@ModifyConstant::getExperienceTextColor(I)I with priority 1000, already redirected by levelz.mixins.json:player.InGameHudMixin from mod levelz->@ModifyConstant::modifyExperienceNumberColor(I)I with priority 1000
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-05-16 17:53:53
Description: Initializing game

java.lang.RuntimeException: Mixin transformation of net.minecraft.class_329 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:603)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 12 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getExperienceTextColor(I)I in vanadium.mixins.json:client.InGameHudMixin from mod vanadium failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap vanadium-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 15 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.minecraft.class_310.<init>(class_310.java:603)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		CoreMessaging.dll:Microsoft CoreMessaging Dll:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		CoreUIComponents.dll:Microsoft Core UI Components Dll:10.0.22621.2506:Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		GLU32.dll:OpenGL Utility Library DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		MpOav.dll:IOfficeAntiVirus Module:4.18.24030.9 (cd8105518e5571788ee3b6a178bae8fbcdf461a8):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OpenAL.dll:Main implementation library:1.21.1:
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		PhysXCommon_64.dll:PhysXCommon 32bit Dynamic Link Library:5.2.1.0:NVIDIA Corporation
		PhysXCooking_64.dll:PhysXCooking 32bit Dynamic Link Library:5.2.1.0:NVIDIA Corporation
		PhysXDevice64.dll:NVIDIA PhysX Device Module:18, 12, 7, 2:NVIDIA Corporation
		PhysXFoundation_64.dll:PhysXFoundation 32bit Dynamic Link Library:5.2.1.0:NVIDIA Corporation
		PhysXGpu_64.dll:PhysXGpu 32bit Dynamic Link Library:5.2.1.0:NVIDIA Corporation
		PhysXJniBindings_64.dll
		PhysX_64.dll:PhysX 32bit Dynamic Link Library:5.2.1.0:NVIDIA Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.22621.2792 (WinBuild.160101.0800):Microsoft Corporation
		Setupapi.dll:Windows Setup API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINSTA.dll:Winstation Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		WINTRUST.DLL:Microsoft Trust Verification APIs:10.0.22621.3447 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WTSAPI32.dll:Windows Remote Desktop Session Host Server SDK APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		cfgmgr32.dll:Configuration Manager DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		cryptnet.dll:Crypto Network Related API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		devobj.dll:Device Information Set DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dinput8.dll:Microsoft DirectInput:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		drvstore.dll:Driver Store API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		dwmapi.dll:Microsoft Desktop Window Manager API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		dxcore.dll:DXCore:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		gpapi.dll:Group Policy Client API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		icm32.dll:Microsoft Color Management Module (CMM):10.0.22621.3085 (WinBuild.160101.0800):Microsoft Corporation
		imagehlp.dll:Windows NT Image Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		inputhost.dll:InputHost:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		java.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		java.exe:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		jemalloc.dll
		jimage.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		jli.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		jna15549047897020982686.dll:JNA native library:6.1.4:Java(TM) Native Access (JNA)
		jsvml.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		jvm.dll:Java HotSpot(TM) 64-Bit server VM:17.0.11.0:Oracle Corporation
		kernel.appcore.dll:AppModel API Host:10.0.22621.2715 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		lwjgl_opengl.dll
		lwjgl_stb.dll
		management.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		management_ext.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		msasn1.dll:ASN.1 Runtime APIs:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mscms.dll:Microsoft Color Matching System DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		msvcp140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		nio.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		ntmarta.dll:Windows NT MARTA provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		nvapi64.dll:NVIDIA NVAPI Library, Version 552.22 :31.0.15.5222:NVIDIA Corporation
		nvcuda.dll:NVIDIA CUDA Driver, Version 552.22 :31.0.15.5222:NVIDIA Corporation
		nvcuda64.dll:NVIDIA CUDA Driver, Version 552.22 :31.0.15.5222:NVIDIA Corporation
		nvgpucomp64.dll:NVIDIA GPU Compiler Driver, Version 552.22 :31.0.15.5222:NVIDIA Corporation
		nvoglv64.dll:NVIDIA Compatible OpenGL ICD:31.0.15.5222:NVIDIA Corporation
		nvspcap64.dll:NVIDIA Game Proxy:3.28.0.412:NVIDIA Corporation
		opengl32.dll:OpenGL Client DLL:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP Name Space Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		powrprof.dll:Power Profile Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		textinputframework.dll:"TextInputFramework.DYNLINK":10.0.22621.3447 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		uxtheme.dll:Microsoft UxTheme Library:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		verify.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
		win32u.dll:Win32u:10.0.22621.3447 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows Base Types DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wldp.dll:Windows Lockdown Policy:10.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		xinput1_4.dll:Microsoft Common Controller API:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:Java(TM) Platform SE binary:17.0.11.0:Oracle Corporation
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Comment by Onnei** [comment]
i fixed it the mod doesnt work with LevelZ

**Comment by nicofighter45** [comment]
I will fix it when my exams ends, thanks for the report 👍
